-- Migration 040: Foundation Layer
--
-- Three things this migration does:
--
-- 1. Quarantine synthesized data — the 613 GPT-generated chapters must never
--    reach the student. quarantined=true is the hard gate.
--
-- 2. student_interactions — raw interaction log from Day 1. Every question
--    viewed, every topic marked weak. This is the moat that accumulates silently.
--
-- 3. get_recurring_topics RPC — powers the first Domino: "أسئلة متكررة".
--    Groups exam_questions by topic_tags across exam years. Supports /bank command.

-- ---------------------------------------------------------------------------
-- 1. Quarantine columns
-- ---------------------------------------------------------------------------

ALTER TABLE kg_syllabi
    ADD COLUMN IF NOT EXISTS quarantined BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE kg_chapters
    ADD COLUMN IF NOT EXISTS quarantined BOOLEAN NOT NULL DEFAULT false;

-- Mark all synthesized syllabi + their chapters as quarantined.
-- These were generated by GPT-4o from program-spec DOCX files — credible structure
-- but NOT official university content. Block from all student-facing surfaces.
UPDATE kg_syllabi
SET quarantined = true
WHERE source_type = 'synthesized';

UPDATE kg_chapters
SET quarantined = true
WHERE syllabus_id IN (
    SELECT id FROM kg_syllabi WHERE source_type = 'synthesized'
);

-- Fast filter: non-quarantined chapters only
CREATE INDEX IF NOT EXISTS kc_non_quarantined_idx
    ON kg_chapters (tenant_id, course_code)
    WHERE quarantined = false;

-- Fast filter: non-quarantined syllabi only
CREATE INDEX IF NOT EXISTS ks_non_quarantined_idx
    ON kg_syllabi (tenant_id, course_code)
    WHERE quarantined = false;

-- ---------------------------------------------------------------------------
-- 2. student_interactions — raw behavior log
-- ---------------------------------------------------------------------------
-- No analysis layer yet. Just capture everything from Day 1.
-- KnowledgeState, mastery scores, and recommendations come later — built on top
-- of this log. Every row here is a data point no competitor can buy.

CREATE TABLE IF NOT EXISTS student_interactions (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
    user_id         UUID        NOT NULL,   -- FK to users.id (pseudonymous)
    interaction     TEXT        NOT NULL,
        -- 'viewed_question'     — student opened a question
        -- 'marked_weak'         — student flagged topic as not understood
        -- 'marked_strong'       — student flagged topic as understood
        -- 'completed_topic'     — student finished reviewing a topic
        -- 'viewed_recurring'    — student viewed recurring questions list
        -- 'shared'              — student shared a result (viral signal)
    entity_type     TEXT        NOT NULL,
        -- 'exam_question' | 'topic' | 'chapter' | 'course_bank'
    entity_id       UUID,                   -- NULL for course_bank views
    course_code     TEXT,
    exam_type       TEXT,                   -- 'midterm' | 'final' | null
    session_id      UUID,                   -- from existing sessions table
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT si_interaction_check CHECK (interaction IN (
        'viewed_question', 'marked_weak', 'marked_strong',
        'completed_topic', 'viewed_recurring', 'shared'
    )),
    CONSTRAINT si_entity_type_check CHECK (entity_type IN (
        'exam_question', 'topic', 'chapter', 'course_bank'
    ))
);

-- Primary read: what did this user interact with?
CREATE INDEX IF NOT EXISTS si_user_course_idx
    ON student_interactions (user_id, course_code, created_at DESC);

-- Analytics: what's popular per course this week?
CREATE INDEX IF NOT EXISTS si_course_time_idx
    ON student_interactions (tenant_id, course_code, created_at DESC)
    WHERE interaction = 'viewed_question';

-- Weak topics per user: the raw material for KnowledgeState
CREATE INDEX IF NOT EXISTS si_weak_topics_idx
    ON student_interactions (user_id, entity_id)
    WHERE interaction = 'marked_weak';

-- ---------------------------------------------------------------------------
-- 3. get_recurring_topics RPC
-- ---------------------------------------------------------------------------
-- Groups exam_questions by topic_tag × exam_year. Returns topics sorted by
-- how many distinct years they appear in — the recurring signal.
-- Used by: GET /v1/exam-bank/{course_code}/recurring in search_api.py

CREATE OR REPLACE FUNCTION get_recurring_topics(
    p_course_code   TEXT,
    p_tenant_id     UUID    DEFAULT '00000000-0000-0000-0000-000000000001',
    p_exam_type     TEXT    DEFAULT NULL,
    p_limit         INT     DEFAULT 15
)
RETURNS TABLE (
    topic_name      TEXT,
    year_count      BIGINT,
    years           TEXT[],
    question_count  BIGINT,
    sample_question TEXT,
    question_types  TEXT[]
)
LANGUAGE SQL STABLE AS $$
    SELECT
        t.tag                               AS topic_name,
        COUNT(DISTINCT eq.exam_year)        AS year_count,
        ARRAY_AGG(DISTINCT eq.exam_year
            ORDER BY eq.exam_year)
            FILTER (WHERE eq.exam_year IS NOT NULL)  AS years,
        COUNT(*)                            AS question_count,
        -- longest question text = most complete sample
        (ARRAY_AGG(eq.question_text
            ORDER BY LENGTH(eq.question_text) DESC))[1]  AS sample_question,
        ARRAY_AGG(DISTINCT eq.question_type)
            FILTER (WHERE eq.question_type != 'unknown') AS question_types
    FROM exam_questions eq
    CROSS JOIN LATERAL unnest(eq.topic_tags) AS t(tag)
    WHERE eq.course_code  = p_course_code
      AND eq.tenant_id    = p_tenant_id
      AND (p_exam_type IS NULL OR eq.exam_type = p_exam_type)
      AND eq.topic_tags  != '{}'
      AND eq.exam_year   IS NOT NULL
    GROUP BY t.tag
    HAVING COUNT(*) >= 1
    ORDER BY year_count DESC, question_count DESC
    LIMIT p_limit
$$;

COMMENT ON FUNCTION get_recurring_topics IS
    'Returns topic tags grouped by recurrence across exam years for a given course. '
    'Powers the /bank command and the Exam Bank screen. '
    'p_exam_type: NULL = all types, or midterm/final/quiz. '
    'Ordered by year_count DESC (most recurring first), then question_count DESC.';
