-- Migration 059: Student Life OS — Core Primitives
--
-- Adds the kernel tables missing from RUMMAN:
--   student_tasks          — personal + academic tasks (the daily driver)
--   student_calendar_events— personal calendar layer on top of official academic calendar
--   student_notifications  — intelligent, ranked notification queue
--
-- These three tables are the foundation of the Student Life OS.
-- Without them, RUMMAN can answer questions but cannot manage a student's day.

-- ── student_tasks ────────────────────────────────────────────────────────────
-- Every task the student needs to do. Auto-generated by RUMMAN or added manually.
-- Linked to course, calendar event, or request — gives context, not just a list.

CREATE TABLE IF NOT EXISTS student_tasks (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id          UUID        NOT NULL REFERENCES rumman_users(id) ON DELETE CASCADE,
    tenant_id           UUID        NOT NULL,

    -- What
    title               TEXT        NOT NULL CHECK (char_length(title) BETWEEN 1 AND 500),
    notes               TEXT,
    task_type           TEXT        NOT NULL DEFAULT 'personal'
                            CHECK (task_type IN (
                                'assignment',   -- واجب دراسي
                                'exam_prep',    -- استعداد لاختبار
                                'deadline',     -- موعد رسمي (حذف، سداد، تسجيل)
                                'request',      -- متابعة طلب إداري
                                'reading',      -- قراءة / مراجعة
                                'personal'      -- مهمة شخصية
                            )),

    -- Priority & Status
    status              TEXT        NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'done', 'snoozed', 'cancelled')),
    priority            SMALLINT    NOT NULL DEFAULT 2
                            CHECK (priority BETWEEN 1 AND 3),  -- 1=urgent 2=normal 3=low

    -- Timing
    due_at              TIMESTAMPTZ,
    snoozed_until       TIMESTAMPTZ,
    remind_at           TIMESTAMPTZ,     -- when to push notification
    acted_on_at         TIMESTAMPTZ,     -- feedback: when did student actually do it

    -- Context links (all optional — task can exist standalone)
    course_code         TEXT,            -- which course does this belong to
    calendar_event_id   UUID,            -- link to student_calendar_events
    request_id          UUID,            -- link to student_requests (migration 060)
    exam_date           DATE,            -- if task_type=exam_prep, which exam

    -- Origin
    auto_generated      BOOL        NOT NULL DEFAULT false,  -- rummaan generated vs student added
    source_ref          TEXT,       -- where did RUMMAN pull this from (intelligence_item id, etc.)

    -- Timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_student_tasks_student_status
    ON student_tasks (student_id, status, due_at NULLS LAST);

CREATE INDEX idx_student_tasks_course
    ON student_tasks (student_id, course_code)
    WHERE course_code IS NOT NULL;

CREATE INDEX idx_student_tasks_due_today
    ON student_tasks (student_id, due_at)
    WHERE status = 'pending' AND due_at IS NOT NULL;


-- ── student_calendar_events ──────────────────────────────────────────────────
-- Personal calendar layer: syncs official academic_calendar events PLUS
-- professor announcements PLUS student's own personal events.
-- This is what the Calendar OS screen reads from.

CREATE TABLE IF NOT EXISTS student_calendar_events (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id          UUID        NOT NULL REFERENCES rumman_users(id) ON DELETE CASCADE,
    tenant_id           UUID        NOT NULL,

    -- What
    title               TEXT        NOT NULL CHECK (char_length(title) BETWEEN 1 AND 500),
    description         TEXT,
    event_type          TEXT        NOT NULL DEFAULT 'personal'
                            CHECK (event_type IN (
                                'lecture',              -- محاضرة
                                'exam',                 -- اختبار
                                'assignment_deadline',  -- موعد تسليم واجب
                                'registration_window',  -- نافذة تسجيل
                                'drop_add_window',      -- حذف وإضافة
                                'withdrawal_deadline',  -- آخر موعد انسحاب
                                'payment_deadline',     -- موعد سداد
                                'holiday',              -- إجازة
                                'official_announcement',-- إعلان رسمي
                                'personal'              -- حدث شخصي
                            )),

    -- Timing
    starts_at           TIMESTAMPTZ NOT NULL,
    ends_at             TIMESTAMPTZ,
    all_day             BOOL        NOT NULL DEFAULT false,

    -- Context
    course_code         TEXT,
    location            TEXT,

    -- Reminders: array of minutes-before to notify
    -- e.g. [60, 1440] = 1 hour before + 1 day before
    reminder_minutes    INT[]       NOT NULL DEFAULT '{60}',

    -- Source
    source              TEXT        NOT NULL DEFAULT 'personal'
                            CHECK (source IN (
                                'official',         -- from academic_calendar
                                'professor',        -- from intelligence_items / Telegram
                                'system',           -- RUMMAN auto-added
                                'personal'          -- student added manually
                            )),
    source_ref_id       UUID,       -- FK to academic_calendar.id or intelligence_items.id

    -- Pinned/hidden
    is_pinned           BOOL        NOT NULL DEFAULT false,
    is_hidden           BOOL        NOT NULL DEFAULT false,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sce_student_window
    ON student_calendar_events (student_id, starts_at)
    WHERE is_hidden = false;

CREATE INDEX idx_sce_course
    ON student_calendar_events (student_id, course_code, starts_at)
    WHERE course_code IS NOT NULL;


-- ── student_notifications ────────────────────────────────────────────────────
-- Intelligent notification queue. RUMMAN writes here; mobile app reads.
-- Every notification has a category, urgency, and an action target so
-- the app can deep-link directly to the relevant screen.

CREATE TABLE IF NOT EXISTS student_notifications (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id          UUID        NOT NULL REFERENCES rumman_users(id) ON DELETE CASCADE,
    tenant_id           UUID        NOT NULL,

    -- Content
    category            TEXT        NOT NULL
                            CHECK (category IN (
                                'decision',         -- action required from student
                                'reminder',         -- time-based task reminder
                                'announcement',     -- professor / institutional news
                                'alert',            -- academic risk or deadline
                                'insight',          -- proactive study intelligence
                                'request_update'    -- status change on a request
                            )),
    urgency             TEXT        NOT NULL DEFAULT 'normal'
                            CHECK (urgency IN ('critical', 'high', 'normal', 'low')),
    title               TEXT        NOT NULL,
    body                TEXT,

    -- Deep-link action
    action_type         TEXT
                            CHECK (action_type IN (
                                'open_task',
                                'open_request',
                                'open_calendar_event',
                                'open_course',
                                'open_copilot',
                                'open_panic_mode',
                                'open_graduation',
                                'open_inbox',
                                'none'
                            )),
    action_ref_id       UUID,       -- ID of the target object
    action_context      JSONB,      -- extra params (e.g. course_code for copilot)

    -- Lifecycle
    scheduled_for       TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at             TIMESTAMPTZ,
    seen_at             TIMESTAMPTZ,
    acted_on_at         TIMESTAMPTZ,    -- feedback loop
    dismissed_at        TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ,    -- auto-expire stale notifications

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sn_student_pending
    ON student_notifications (student_id, scheduled_for, urgency)
    WHERE seen_at IS NULL AND dismissed_at IS NULL;

CREATE INDEX idx_sn_student_feed
    ON student_notifications (student_id, created_at DESC)
    WHERE dismissed_at IS NULL;


-- ── Helper function: get_student_active_courses ──────────────────────────────
-- Infers a student's active courses from their recent learning_events.
-- Used by the Home Command Center and Calendar OS until Banner integration.

CREATE OR REPLACE FUNCTION get_student_active_courses(
    p_student_id UUID,
    p_tenant_id  UUID,
    p_days       INT DEFAULT 30
)
RETURNS TABLE (course_code TEXT, last_active TIMESTAMPTZ, query_count INT)
LANGUAGE sql STABLE AS $$
    SELECT
        unnested.code                           AS course_code,
        MAX(le.occurred_at)                     AS last_active,
        COUNT(*)::INT                           AS query_count
    FROM   learning_events le,
           UNNEST(le.course_codes) AS unnested(code)
    WHERE  le.user_id    = p_student_id
      AND  le.tenant_id  = p_tenant_id
      AND  le.occurred_at >= now() - (p_days || ' days')::INTERVAL
      AND  unnested.code IS NOT NULL
    GROUP  BY unnested.code
    ORDER  BY MAX(le.occurred_at) DESC;
$$;


-- ── Helper function: get_student_today ───────────────────────────────────────
-- Returns the Home Command Center payload for a student:
-- today's tasks, upcoming deadlines within 7 days, and open notifications.

CREATE OR REPLACE FUNCTION get_student_today(
    p_student_id UUID,
    p_tenant_id  UUID
)
RETURNS JSON
LANGUAGE plpgsql STABLE AS $$
DECLARE
    v_tasks         JSON;
    v_events        JSON;
    v_notifications JSON;
    v_courses       JSON;
BEGIN
    -- Today's pending tasks + overdue
    SELECT json_agg(t ORDER BY t.priority ASC, t.due_at ASC NULLS LAST)
    INTO   v_tasks
    FROM   student_tasks t
    WHERE  t.student_id = p_student_id
      AND  t.tenant_id  = p_tenant_id
      AND  t.status     = 'pending'
      AND  (t.due_at IS NULL OR t.due_at::DATE <= (now() + INTERVAL '1 day')::DATE);

    -- Calendar events in next 7 days
    SELECT json_agg(e ORDER BY e.starts_at ASC)
    INTO   v_events
    FROM   student_calendar_events e
    WHERE  e.student_id = p_student_id
      AND  e.tenant_id  = p_tenant_id
      AND  e.is_hidden  = false
      AND  e.starts_at  BETWEEN now() AND now() + INTERVAL '7 days';

    -- Unread notifications ordered by urgency + recency
    SELECT json_agg(n ORDER BY
        CASE n.urgency WHEN 'critical' THEN 1 WHEN 'high' THEN 2
                       WHEN 'normal'   THEN 3 ELSE 4 END,
        n.created_at DESC)
    INTO   v_notifications
    FROM   student_notifications n
    WHERE  n.student_id   = p_student_id
      AND  n.tenant_id    = p_tenant_id
      AND  n.seen_at      IS NULL
      AND  n.dismissed_at IS NULL
      AND  (n.expires_at IS NULL OR n.expires_at > now())
      AND  n.scheduled_for <= now()
    LIMIT  20;

    -- Active courses with query volume
    SELECT json_agg(c)
    INTO   v_courses
    FROM   get_student_active_courses(p_student_id, p_tenant_id, 30) c;

    RETURN json_build_object(
        'tasks',         COALESCE(v_tasks, '[]'::JSON),
        'events',        COALESCE(v_events, '[]'::JSON),
        'notifications', COALESCE(v_notifications, '[]'::JSON),
        'active_courses',COALESCE(v_courses, '[]'::JSON)
    );
END;
$$;
